name: linting
on:
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:
jobs:
    sqlfluff-lint-annotations-native:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          pull-requests: write 

        steps:
            - uses: actions/checkout@v4
            - run: pip install 'sqlfluff==3.4.0' 
            - name: Run sqlfluff linter with github native annotations
              run: |
                sqlfluff lint -f github-annotation-native $(git diff --name-only ${{ github.base_ref }})
